---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt: 
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    state: present

- name: Creates directory
  file:
    path: ~/working
    state: directory

- name: Copy file1
  template:
    src: "playbook.yml"
    dest: "~/playbook.yml"

- name: Copy file2
  template:
    src: "inventory"
    dest: "~/inventory"
    
 - name: Copy directory roles
  template:
    src: "roles/"
    dest: "~/roles/"
