version: 2.1

jobs:
  configure_infrastructure:
    docker: 
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: [E6:89:09:70:3E:F0:CE:FA:E6:B0:22:58:9B:01:CF:02:C6:D5:C2:B6]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible # install the dependencies
      - run:
          name: Configure server
          command: |
            export ANSIBLE_HOST_KEY_CHECKING=False
            ansible-playbook  ./playbook.yml  -i ./inventory.txt
            
workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
